Repository vitspot/dsa-roadmaps, pull requests merged in 2021-10, with the labels that each got.

#4 Binary Tree, 3 questions added
  dsa-roadmaps/Love Babbar Questions/Binary trees/Boundary Traversal/BoundaryTraversal.cpp
  dsa-roadmaps/Love Babbar Questions/Binary trees/Boundary Traversal/readme.md
  dsa-roadmaps/Love Babbar Questions/Binary trees/Top View/TopView.cpp
  dsa-roadmaps/Love Babbar Questions/Binary trees/Top View/readme.md
  dsa-roadmaps/Love Babbar Questions/Binary trees/Zig Zag Traversal/ZigZag.cpp
  dsa-roadmaps/Love Babbar Questions/Binary trees/Zig Zag Traversal/readme.md
Labels: hacktoberfest-accepted

#3 Added Data Structure II
  dsa-roadmaps/LeetCode Study Plan/Data Structure/Data Structure - 2/3Sum/readme.md
  dsa-roadmaps/LeetCode Study Plan/Data Structure/Data Structure - 2/3Sum/solution.cpp
  dsa-roadmaps/LeetCode Study Plan/Data Structure/Data Structure - 2/Majority Element/readme.md
  dsa-roadmaps/LeetCode Study Plan/Data Structure/Data Structure - 2/Majority Element/solution.cpp
  dsa-roadmaps/LeetCode Study Plan/Data Structure/Data Structure - 2/Single Number/readme.md
  dsa-roadmaps/LeetCode Study Plan/Data Structure/Data Structure - 2/Single Number/solution.cpp
Labels: hacktoberfest-accepted

#7 Added 3 solutions of Linked List problems(Love Babbar Questions)
  dsa-roadmaps/Love Babbar Questions/Linked List/Clone linked list(random pointer)/readme.md
  dsa-roadmaps/Love Babbar Questions/Linked List/Clone linked list(random pointer)/solution.java
  dsa-roadmaps/Love Babbar Questions/Linked List/Detect loop in linked list/readme.md
  dsa-roadmaps/Love Babbar Questions/Linked List/Detect loop in linked list/solution.java
  dsa-roadmaps/Love Babbar Questions/Linked List/Middle of Linked List/readme.md
  dsa-roadmaps/Love Babbar Questions/Linked List/Middle of Linked List/solution.java
Labels: hacktoberfest-accepted, contributor

#8 Added 3 questions of Linked Lists
  dsa-roadmaps/Love Babbar Questions/Linked List/Palindrome/PlaindromeLL.cpp
  dsa-roadmaps/Love Babbar Questions/Linked List/Palindrome/readme.md
  dsa-roadmaps/Love Babbar Questions/Linked List/RotateByN/RotateDLLbyN.cpp
  dsa-roadmaps/Love Babbar Questions/Linked List/RotateByN/readme.md
  dsa-roadmaps/Love Babbar Questions/Linked List/SplitList/SplitList.cpp
  dsa-roadmaps/Love Babbar Questions/Linked List/SplitList/readme.md
Labels: hacktoberfest-accepted, contributor

#9 Added Arrays Solutions
  dsa-roadmaps/Love Babbar Questions/Arrays/Cyclically rotate an array by one/readme.md
  dsa-roadmaps/Love Babbar Questions/Arrays/Cyclically rotate an array by one/solution.cpp
  dsa-roadmaps/Love Babbar Questions/Arrays/Move all negative elements to end/readme.md
  dsa-roadmaps/Love Babbar Questions/Arrays/Move all negative elements to end/solution.cpp
  dsa-roadmaps/Love Babbar Questions/Arrays/Union of two arrays/readme.md
  dsa-roadmaps/Love Babbar Questions/Arrays/Union of two arrays/solution.cpp
Labels: hacktoberfest-accepted, contributor

#10 Added solutions LC study plan algorithms-1
  dsa-roadmaps/LeetCode Study Plan/Algorithms/ALgorithm-1/Binary Search/readme.md
  dsa-roadmaps/LeetCode Study Plan/Algorithms/ALgorithm-1/Binary Search/solution.cpp
  dsa-roadmaps/LeetCode Study Plan/Algorithms/ALgorithm-1/First Bad Version/readme.md
  dsa-roadmaps/LeetCode Study Plan/Algorithms/ALgorithm-1/First Bad Version/solution.cpp
  dsa-roadmaps/LeetCode Study Plan/Algorithms/ALgorithm-1/Search Insert Position/readme.md
  dsa-roadmaps/LeetCode Study Plan/Algorithms/ALgorithm-1/Search Insert Position/solution.cpp
Labels: hacktoberfest-accepted, contributor

#30 Add new Algorithms folder for Beginners
  dsa-roadmaps/Beginners/Algorithms/Graphs/Breadth-First-Search.c
  dsa-roadmaps/Beginners/Algorithms/Graphs/Dijsktra-Algorithm.c
  dsa-roadmaps/Beginners/Algorithms/README.md
  dsa-roadmaps/Beginners/Algorithms/Sorting/Quick-Sort.c
Labels: hacktoberfest-accepted, contributor

#31 leetcode algorithms-1/Day-1/python-solution
  dsa-roadmaps/LeetCode Study Plan/Algorithms/ALgorithm-1/Day 1 - Binary Search/278. First Bad Version/solution1.py
  dsa-roadmaps/LeetCode Study Plan/Algorithms/ALgorithm-1/Day 1 - Binary Search/35. Search Insert Position/solution1.py
  dsa-roadmaps/LeetCode Study Plan/Algorithms/ALgorithm-1/Day 1 - Binary Search/704. Binary Search/solution1.py
Labels: contributor

#28 added 3 questions in Binary Tree
  dsa-roadmaps/Love Babbar Questions/Binary Search Trees/Find a value in BST/readme.md
  dsa-roadmaps/Love Babbar Questions/Binary trees/Height of Binary Tree/Height of Binary Tree.cpp
  dsa-roadmaps/Love Babbar Questions/Binary trees/Height of Binary Tree/readme.md
  dsa-roadmaps/Love Babbar Questions/Binary trees/Level Order Traversal/Level Order Traversal.cpp
  dsa-roadmaps/Love Babbar Questions/Binary trees/Level Order Traversal/readme.md
  dsa-roadmaps/Love Babbar Questions/Binary trees/Reverse Level Order Traversal/Reverse Level Order Traversal .cpp
  dsa-roadmaps/Love Babbar Questions/Binary trees/Reverse Level Order Traversal/readme.md
  dsa-roadmaps/Love Babbar Questions/Searching & Sorting/Majority Element/Majority Element.cpp
  dsa-roadmaps/Love Babbar Questions/Searching & Sorting/Majority Element/readme.md
  dsa-roadmaps/Love Babbar Questions/Searching & Sorting/Merge Without Extra Space/Merge Without Extra Space.cpp
  dsa-roadmaps/Love Babbar Questions/Searching & Sorting/Merge Without Extra Space/readme.md
  dsa-roadmaps/Love Babbar Questions/Searching & Sorting/Pair with Given Diffrence/Pair with Given Difference.cpp
  dsa-roadmaps/Love Babbar Questions/Searching & Sorting/Pair with Given Diffrence/readme.md
Labels: hacktoberfest-accepted, contributor
